import type { Dictionary } from '@/content/types'

type Common = Omit<Dictionary, 'servicesIndex' | 'servicePages' | 'images'>

export const common: Common = {
  locale: 'en',
  site: {
    tagline: 'Christmas décor, delivered, installed and styled in Dubai & Sharjah',
    description:
      'Everpine Events supplies, delivers, installs and styles Christmas trees, door arches, wreaths, staircase garlands, table décor and house lighting for villas, homes and businesses in Dubai and Sharjah. Packages from AED 5,500.',
  },
  nav: {
    home: 'Home',
    packages: 'Packages',
    services: 'Services',
    commercial: 'For businesses',
    gallery: 'Gallery',
    about: 'About',
    faq: 'FAQ',
    contact: 'Get a quote',
    guides: 'Guides',
    dubai: 'Dubai',
    sharjah: 'Sharjah',
    menu: 'Menu',
    close: 'Close',
    skip: 'Skip to content',
    primary: 'Main',
    footer: 'Footer',
    breadcrumb: 'Breadcrumb',
  },
  cta: {
    whatsapp: 'Plan it on WhatsApp',
    whatsappShort: 'WhatsApp',
    call: 'Call',
    email: 'Email',
    quote: 'Get a quote',
    viewPackages: 'See the packages',
    choose: (pkg) => `Choose ${pkg}`,
    enquireForm: 'Enquire by form',
    bookEarly: 'Limited installation slots each season — book early.',
    seeGallery: 'See the gallery',
    readGuide: 'Read the guide',
  },
  season: {
    booking: {
      eyebrow: 'Now booking · Christmas {year}',
      line: 'Limited installation slots each season — book early.',
      ctaPrimary: 'Get a quote',
    },
    'in-season': {
      eyebrow: 'Christmas {year} · Installations underway',
      line: 'Limited installation slots each season — ask about remaining dates.',
      ctaPrimary: 'Check availability',
    },
    'off-season': {
      eyebrow: 'Now booking for Christmas {year}',
      line: 'Limited installation slots each season — plan early and book first.',
      ctaPrimary: 'Reserve a consultation',
    },
  },
  whatsappMessages: {
    general: 'Hello Everpine, I’d like to plan Christmas décor.',
    package: (name, price) =>
      `Hello Everpine, I’m interested in the ${name} package (${price}). Could you share availability and next steps?`,
    service: (service) => `Hello Everpine, I’d like a quote for ${service}.`,
  },
  packages: {
    heading: 'The Collection',
    intro:
      'Three complete compositions, each delivered, installed and styled by our team. Choose the one that suits your space, or ask us to build something of your own.',
    includeLabels: {
      tree: 'Christmas tree, styled',
      treeSkirt: 'Cloth tree skirt',
      giftBoxes: 'Gift boxes',
      doorArch: 'Door arch',
      wreath: 'Wreath',
      stairDecoration: 'Stair decoration',
      tableDecoration: 'Table decoration',
      figurines: 'Figurines',
      houseLighting: 'House lighting',
    },
    items: {
      basic: {
        name: 'Basic',
        numeral: 'I',
        tagline: 'The essential welcome',
        summary:
          'A 2.4 m tree for the living room and a finished entrance — door arch and wreath — so the house feels ready from the moment guests arrive.',
        idealFor: 'Apartments and homes with standard ceiling heights',
        image: 'package-basic',
        detailImage: 'evergreen-door-arch-red-gold-baubles-wreath-white-door',
      },
      silver: {
        name: 'Silver',
        numeral: 'II',
        tagline: 'The house, dressed',
        summary:
          'A taller 2.7 m tree with gift boxes beneath, the entrance framed and wreathed, and the staircase garlanded — the whole route from front door to living room.',
        idealFor: 'Townhouses and villas with a staircase',
        image: 'package-silver',
        detailImage: 'staircase-cream-gold-garland-bows-iron-balustrade',
      },
      gold: {
        name: 'Gold',
        numeral: 'III',
        tagline: 'Inside and out',
        summary:
          'A statement 3–3.6 m tree, entrance, staircase, dining table and figurines — plus house lighting, so the villa glows from the street when evening falls.',
        idealFor: 'Villas with double-height spaces and outdoor frontage',
        image: 'package-gold',
        detailImage: 'villa-facade-icicle-lights-reindeer-dusk',
      },
    },
    priceNote: 'Delivery, installation and styling included. Final quote confirmed on enquiry.',
    included: 'Included',
    notIncluded: 'Removal after the season is available as a separate service.',
    heightLabel: 'Tree height',
    ceilingLabel: 'Ceiling',
    whatArrives: 'What arrives',
    from: 'from',
  },
  gallery: {
    typeLabels: {
      trees: 'Trees',
      entrances: 'Door arches & wreaths',
      stairs: 'Stairs & garlands',
      tables: 'Tables & figurines',
      lighting: 'Lighting',
      commercial: 'Businesses',
      process: 'Installation',
    },
    paletteLabels: {
      'red-gold': 'Red & gold',
      'frost-silver': 'Frost & silver',
      'emerald-gold': 'Emerald & gold',
      'bronze-champagne': 'Bronze & champagne',
      peppermint: 'Peppermint',
      'quiet-neutral': 'Quiet neutrals',
    },
    all: 'All work',
    filterBy: 'Filter by',
    showing: (n) => `Showing ${n} ${n === 1 ? 'installation' : 'installations'}`,
  },
  areas: {
    dubai: 'Dubai',
    sharjah: 'Sharjah',
  },
  footer: {
    statement: 'Christmas, delivered, installed and styled — for villas, homes and businesses in Dubai and Sharjah.',
    servicesHeading: 'Services',
    areasHeading: 'Areas',
    companyHeading: 'Everpine',
    contactHeading: 'Contact',
    contactPending: 'Send us your details and we’ll reply to arrange your quote.',
    legal: 'All rights reserved.',
    privacy: 'Privacy policy',
    provisional: '',
  },
  form: {
    heading: 'Request a quote',
    intro: 'Takes about a minute — only your name, phone, area and property type are required.',
    fields: {
      name: 'Your name',
      phone: 'Phone / WhatsApp',
      email: 'Email',
      area: 'Area',
      propertyType: 'Property type',
      package: 'Package',
      date: 'Preferred installation date',
      dateHint: 'An approximate date is fine.',
      message: 'Anything we should know?',
      messagePlaceholder: 'Ceiling height, colour palette, rooms to decorate, access notes…',
      optional: 'optional',
    },
    propertyTypes: {
      villa: 'Villa',
      apartment: 'Apartment',
      townhouse: 'Townhouse',
      office: 'Office',
      hotel: 'Hotel',
      restaurant: 'Restaurant or café',
      retail: 'Retail',
      other: 'Other',
    },
    packageOptions: {
      basic: 'Basic — AED 5,500',
      silver: 'Silver — AED 14,800',
      gold: 'Gold — AED 24,700',
      custom: 'Custom / not sure yet',
    },
    submit: 'Send enquiry',
    sending: 'Sending…',
    privacyNote: 'We use these details only to reply to your enquiry. See our [privacy policy](/privacy-policy).',
    success: {
      heading: 'Thank you — your enquiry is with us.',
      body: 'We’ll be in touch to confirm the details and your quote.',
    },
    whatsapp: {
      submit: 'Send on WhatsApp',
      successHeading: 'Almost there — just tap Send in WhatsApp.',
      successBody: 'WhatsApp has opened with your enquiry already written. Send it and we’ll reply to confirm the details and your quote.',
      open: 'Open WhatsApp again',
      greeting: 'Hello Everpine, I’d like a quote for Christmas décor.',
      labels: { name: 'Name', phone: 'Phone', email: 'Email', area: 'Area', propertyType: 'Property', package: 'Package', date: 'Preferred date', notes: 'Notes' },
    },
    errors: {
      generic: 'Something went wrong and your enquiry wasn’t sent. Please try again in a moment.',
      rateLimited: 'You’ve sent several enquiries in a short time. Please wait a few minutes and try again.',
      notConfigured: 'Online enquiries are temporarily unavailable. Please try again later.',
      required: 'Please fill this in.',
      email: 'Please enter a valid email address.',
      phone: 'Please enter a valid phone number, including the country code if outside the UAE.',
      date: 'Please choose a date from today onwards.',
      tooLong: 'Please keep this under 2,000 characters.',
    },
  },
  ui: {
    closingDefault: 'Let’s dress the house for December.',
    threeCompositions: 'Three compositions',
    chooseComposition: ['Choose your', 'composition'],
    tree: 'tree',
    removalLink: 'Post-Christmas removal',
    treeSizeLink: 'Which tree height fits your ceiling?',
    questions: 'Questions',
    related: 'Related',
    alsoIn: 'Also in [Dubai](/christmas-decoration-dubai) and [Sharjah](/christmas-decoration-sharjah).',
    faq: 'FAQ',
    allQuestions: 'All questions',
    houseLighting: 'House lighting',
    plate: 'Plate',
    christmasDecorationIn: (area) => `Christmas decoration in ${area}`,
    cityFaqHeading: (area) => `Christmas décor in ${area}: questions`,
    questionsAbout: (topic) => `${topic}: questions`,
    christmasDecoratorsIn: (area) => `Christmas decorators in ${area}`,
    villaDubai: 'Villa Christmas decoration, Dubai',
    luxuryDubai: 'Luxury Christmas decoration, Dubai',
    cityMessage: (area) => `Hello Everpine, I’d like to plan Christmas décor in ${area}.`,
    custom: 'Custom',
    onQuote: 'On quote',
    businessFaqHeading: 'Questions from businesses',
    businessCtaHeading: 'Brief us early — the best dates go first.',
    businessService: 'Christmas décor for our business',
    galleryType: 'Type',
    galleryOpen: 'View larger',
    galleryClose: 'Close',
    galleryPrev: 'Previous photo',
    galleryNext: 'Next photo',
    galleryZoom: 'Tap the photo to zoom',
    galleryPalette: 'Palette',
    galleryCtaHeading: 'Seen one you love? Send it to us.',
    faqSections: 'FAQ sections',
    faqCtaHeading: 'Still wondering? Ask us directly.',
    quickAnswers: 'Quick answers',
    updated: (d) => `Updated ${d}`,
    lastUpdated: (d) => `Last updated ${d}`,
    treeSizeGuide: 'Tree size guide',
    officeGuide: 'Office décor guide',
    treeSizeGuideShort: 'Tree size for your ceiling',
    officeGuideShort: 'Planning office décor',
    included: 'Included',
    notIncluded: 'Not included',
    deliveryInstallStyling: 'Delivery, installation & styling',
    packagePrice: 'Package price',
    teaserHeading: ['Christmas decoration', 'packages'],
    compareAll: 'See what each package includes',
    newInTier: 'New in this package',
    finalQuote: 'Final quote confirmed on enquiry.',
    nights: 'nights to Christmas',
    night: 'night to Christmas',
    xmasToday: 'Merry Christmas from Everpine',
  },
  consent: {
    text: 'We’d like to use Google Analytics cookies to understand how visitors use this site. You can say no — the site works the same.',
    accept: 'Accept',
    decline: 'No thanks',
    privacyLink: 'Privacy policy',
  },
}
